export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNIN_RESULT = 'USER_SIGNIN_RESULT';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_RESULT = 'USER_SIGNUP_RESULT';

export const USER_DETAILS = 'USER_DETAILS';
export const USER_DETAILS_RESULT = 'USER_DETAILS_RESULT';

export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PASSWORD_RESULT = 'SET_PASSWORD_RESULT';

export const SUBMIT_USER_PROFILE_BASIC_DETAILS = 'SUBMIT_USER_PROFILE_BASIC_DETAILS';
export const SUBMIT_USER_PROFILE_BASIC_DETAILS_RESULT = 'SUBMIT_USER_PROFILE_BASIC_DETAILS_RESULT';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_RESULT = 'FORGOT_PASSWORD_RESULT';

export const USER_LOGOUT = 'USER_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

