export const ADD_STUDENTS_TRIGGER = 'ADD_STUDENTS_TRIGGER';
export const ADD_STUDENTS_RESULT = 'ADD_STUDENTS_RESULT';

export const GET_STUDENTS_TRIGGER = 'GET_STUDENTS_TRIGGER';
export const GET_STUDENTS_RESULT = 'GET_STUDENTS_RESULT';

export const ADD_BATCH_TRIGGER = 'ADD_BATCH_TRIGGER';
export const ADD_BATCH_RESULT = 'ADD_BATCH_RESULT';

export const GET_BATCH_TRIGGER = 'GET_BATCH_TRIGGER';
export const GET_BATCH_RESULT = 'GET_BATCH_RESULT';

export const LOG_ERROR = 'LOG_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';